version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    deploy:
      resources:
        limits:
          memory: 2G

  citus:
    container_name: citus
    image: citusdata/citus
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
