version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.5
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
